Creeds:
  Akwal:
    Menu:
      Icon: WATER_BUCKET
      X: 1
      Y: 1
    Description: Followers of Akwal are seafaring and skilled at fishing - These people have been granted the ability of breathing under water in return for their faith in Akwal.
    Permissions:
    - -modifyworld.damage.take.drowning
    - mcmmo.ability.fishing.*
    Spells:
    - WaterWalk
    - Bang Fish
  Cavilon:
    Menu:
      Icon: STONE
      X: 2
      Y: 1
    Permissions:
    - mcmmo.ability.(mining|excavation|repair).*
  Netharna:
    Menu:
      Icon: LAVA_BUCKET
      X: 4
      Y: 1
    Description: Goddess of Fire and Lava
    Permissions:
    - -modifyworld.damage.take.(fire|firetick|lava)
  Deserma:
    Menu:
      Icon: SAND
      X: 4
      Y: 1
    Description: Goddess of Sand
    Permissions:
    - -modifyworld.damage.take.(fire|firetick|lava)