DayNames:
- Planu
- Akwal
- Cavilon
- Wintival
- Netharna
- Wildaven
- Deserma
YearNames:
- Sheep
- Spider
- Wolf
- Dragon
- Bat
- Slime
- Cow
- Pig
- Ocelot
- Chicken 
Months:
  Coal:
    Days: 31
  Diamond:
    Days: 28
  Grass:
    Days: 31
  Gold:
    Days: 30
  Iron:
    Days: 31
  Lapis:
    Days: 30
  Redstone:
    Days: 31
  Stone:
    Days: 31
  Flint:
    Days: 30
  Dirt:
    Days: 31
  Clay:
    Days: 30
  Emerald:
    Days: 31
Current:
  Date: 1
  

