Skills:
  # X=1
  Swordsmanship:
    Cost: 1000
    Menu:
      Icon: IRON_SWORD
      X: 1
      Y: 1
    Permissions:
    - mcmmo.ability.swords.*
    Description: The way of the sword.
  Berserking:
    Cost: 1000
    Menu:
      Icon: IRON_AXE
      X: 1
      Y: 2
    Permissions:
    - mcmmo.ability.axes.*
    Description: We all know axes look scarier.
  Unarmed:
    Cost: 1000
    Menu:
      Icon: STICK
      X: 1
      Y: 3
    Permissions:
    - mcmmo.ability.unarmed.*
    Description: Ouch.
  Archery:
    Cost: 1000
    Menu:
      Icon: BOW
      X: 1
      Y: 4
    Permissions:
    - mcmmo.ability.archery.*
    Description: Pew pew.
  Acrobatics:
    Cost: 1000
    Menu:
      Icon: LEATHER_BOOTS
      X: 1
      Y: 5
    Permissions:
    - mcmmo.ability.acrobatics.*
    Description: Parkour!
  # X=2
  Excavation:
    Cost: 1000
    Menu:
      Icon: IRON_SPADE
      X: 2
      Y: 1
    Permissions:
    - mcmmo.ability.excavation.*
    Description: Diggin' it up.
  Mining:
    Cost: 1000
    Menu:
      Icon: IRON_PICKAXE
      X: 2
      Y: 2
    Permissions:
    - mcmmo.ability.mining.*
    Description: So thats what pickaxes are for.
  Woodcutting:
    Cost: 1000
    Menu:
      Icon: IRON_AXE
      X: 2
      Y: 3
    Permissions:
    - mcmmo.ability.woodcutting.*
    Description: So thats what pickaxes are for.
  Repair:
    Cost: 1000
    Menu:
      Icon: IRON_BLOCK
      X: 2
      Y: 3
    Permissions:
    - mcmmo.ability.repair.*
    Description: Now I can fix stuff.
  Smelting:
    Cost: 1000
    Menu:
      Icon: IRON_AXE
      X: 2
      Y: 4
    Permissions:
    - mcmmo.ability.smelting.*
    Description: Finally a use for all that ore.
  #X=3
  Fishing:
    Cost: 1000
    Menu:
      Icon: FISHING_ROD
      X: 3
      Y: 1
    Permissions:
    - mcmmo.ability.fishing.*
    Description: I got a big one!
  Taming:
    Cost: 1000
    Menu:
      Icon: LEASH
      X: 3
      Y: 2
    Permissions:
    - mcmmo.ability.taming.*
    Description: Here boy...
  Herbalism:
    Cost: 1000
    Menu:
      Icon: IRON_HOE
      X: 3
      Y: 3
    Permissions:
    - mcmmo.ability.herbalism.*
    Description: It's alive!
  #X=4
  Alchemy:
    Cost: 1000
    Menu:
      Icon: POTION
      X: 4
      Y: 1
    Permissions:
    - mcmmo.ability.alchemy.*
    Description: 3 years later...
  